CREATE TABLE pc_ojxu4t_orderful_work
(
    pxapplication character varying(64),
    pxapplicationversion character varying(32),
    pxcommitdatetime timestamp without time zone,
    pxcoveredcount numeric(18),
    pxcoveredcountopen numeric(18),
    pxcoveredcountunsatisfied numeric(18),
    pxcoverinskey character varying(255),
    pxcreatedatetime timestamp without time zone,
    pxcreateoperator character varying(128),
    pxcreateopname character varying(128),
    pxcreatesystemid character varying(32),
    pxcurrentstage character varying(32),
    pxcurrentstagelabel character varying(128),
    pxexternalsystemupdatecount numeric(18),
    pxflowcount numeric(18),
    pxinsname character varying(128),
    pxobjclass character varying(96),
    pxsavedatetime timestamp without time zone,
    pxupdatedatetime timestamp without time zone,
    pxupdateoperator character varying(128),
    pxupdateopname character varying(128),
    pxupdatesystemid character varying(32),
    pxurgencywork numeric(18),
    pyacktimestamp timestamp without time zone,
    pyagefromdate timestamp without time zone,
    pychargeamount numeric(18),
    pychargeto character varying(64),
    pycontactchannel character varying(64),
    pycontacttype character varying(64),
    pycuslevel character varying(32),
    pycustomer character varying(128),
    pycustomerenterprise character varying(32),
    pycustomername character varying(64),
    pycustomerorg character varying(32),
    pycustomersatisfiedtimestamp timestamp without time zone,
    pydescription character varying(255),
    pyeffortactual numeric(18),
    pyeffortestimate numeric(18),
    pyeffortestimatetimestamp timestamp without time zone,
    pyelapsedcustomerack numeric(18),
    pyelapsedcustomerunsatisfied numeric(18),
    pyelapsedpastdeadline numeric(18),
    pyelapsedpastgoal numeric(18),
    pyelapsedstatusnew numeric(18),
    pyelapsedstatusopen numeric(18),
    pyelapsedstatuspending numeric(18),
    pyeventid character varying(32),
    pyfoldertype character varying(32),
    pyid character varying(32),
    pylabel character varying(64),
    pyorigdivision character varying(32),
    pyorigorg character varying(32),
    pyorigorgunit character varying(32),
    pyoriguserdivision character varying(32),
    pyoriguserid character varying(128),
    pyoriguserworkgroup character varying(64),
    pyownerdivision character varying(32),
    pyownerorg character varying(32),
    pyownerorgunit character varying(32),
    pyprimarycontact character varying(64),
    pyproblemreason character varying(64),
    pyproblemsource character varying(64),
    pyproblemtype character varying(64),
    pyreopencount numeric(18),
    pyreopentimestamp timestamp without time zone,
    pyresolutioncomplexity character varying(8),
    pyresolutioncost numeric(18),
    pyresolveddivision character varying(32),
    pyresolvedorg character varying(32),
    pyresolvedorgunit character varying(32),
    pyresolvedtime character varying(32),
    pyresolvedtimestamp timestamp without time zone,
    pyresolveduserid character varying(128),
    pyresolveduserworkgroup character varying(64),
    pyrootcause character varying(64),
    pysladeadline timestamp without time zone,
    pyslagoal timestamp without time zone,
    pyslaname character varying(32),
    pystatuscustomersat character varying(32),
    pystatuswork character varying(32),
    pyworklistdate1 character varying(8),
    pyworklistdatetime1 timestamp without time zone,
    pyworklistdatetime2 timestamp without time zone,
    pyworklistdecimal1 numeric(18),
    pyworklistdecimal2 numeric(18),
    pyworklistinteger1 numeric(18),
    pyworklisttext1 character varying(128),
    pyworklisttext2 character varying(128),
    pyworklisttext3 character varying(128),
    pzinskey character varying(255) NOT NULL,
    pzpvstream bytea,
    CONSTRAINT pc_ojxu4t_orderful_work_pk PRIMARY KEY (pzinskey)
);