CREATE TABLE pc_history_ojxu4t_orderful_wor
(
    pxaddedbyid character varying(128),
    pxaddedbysystem character varying(64),
    pxassignmentelapsedtime numeric(18),
    pxassignmentpastdeadline numeric(18),
    pxassignmentpastgoal numeric(18),
    pxclienttimecreated timestamp without time zone,
    pxcommitdatetime timestamp without time zone,
    pxcoverinskey character varying(255),
    pxeffortactualdelta numeric(18, 3),
    pxflowaction character varying(32),
    pxhistoryforreference character varying(255),
    pxinsname character varying(255),
    pxlatitude numeric(19, 9),
    pxlongitude numeric(19, 9),
    pxobjclass character varying(96),
    pxresolutioncostdelta numeric(18, 3),
    pxsavedatetime timestamp without time zone,
    pxtaskelapsedtime numeric(18),
    pxtimecreated timestamp without time zone,
    pxtimeflowstarted character varying(64),
    pyassignedto character varying(128),
    pyassignedtoworkgroup character varying(64),
    pyassignmentclass character varying(96),
    pyflowkey character varying(255),
    pyflowname character varying(64),
    pyflowtype character varying(64),
    pyhistorytype character varying(1),
    pylabel character varying(64),
    pymemo character varying(255),
    pymessagekey character varying(1024),
    pyperformactiontime numeric(18),
    pyperformassignmenttime numeric(18),
    pyperformer character varying(128),
    pyperformtasktime numeric(18),
    pysubstitutionvalues character varying(1024),
    pytaskid character varying(64),
    pytaskname character varying(128),
    pyworkclass character varying(64),
    pzinskey character varying(255) NOT NULL,
    CONSTRAINT history_ojxu4t_orderful_wor_pk PRIMARY KEY (pzinskey)
);