CREATE TABLE "pc_ninja_demo"
(
  "pxcoverinskey"                VARCHAR(255),
  "pxcoveredcount"               NUMERIC(18, 0),
  "pxcoveredcountopen"           NUMERIC(18, 0),
  "pxcoveredcountunsatisfied"    NUMERIC(18, 0),
  "pxcreatedatetime"             TIMESTAMP(6),
  "pxcreateopname"               VARCHAR(128),
  "pxcreateoperator"             VARCHAR(128),
  "pxcreatesystemid"             VARCHAR(32),
  "pxflowcount"                  NUMERIC(18, 0),
  "pxinsname"                    VARCHAR(128),
  "pxobjclass"                   VARCHAR(96),
  "pxupdatedatetime"             TIMESTAMP(6),
  "pxupdateopname"               VARCHAR(128),
  "pxupdateoperator"             VARCHAR(128),
  "pxupdatesystemid"             VARCHAR(32),
  "pxurgencywork"                NUMERIC(18, 0),
  "pyacktimestamp"               TIMESTAMP(6),
  "pyagefromdate"                TIMESTAMP(6),
  "pychargeamount"               NUMERIC(18, 0),
  "pychargeto"                   VARCHAR(64),
  "pycontactchannel"             VARCHAR(64),
  "pycontacttype"                VARCHAR(64),
  "pycuslevel"                   VARCHAR(32),
  "pycustomer"                   VARCHAR(128),
  "pycustomerenterprise"         VARCHAR(32),
  "pycustomername"               VARCHAR(64),
  "pycustomerorg"                VARCHAR(32),
  "pycustomersatisfiedtimestamp" TIMESTAMP(6),
  "pydescription"                VARCHAR(255),
  "pyeffortactual"               NUMERIC(18, 0),
  "pyeffortestimate"             NUMERIC(18, 0),
  "pyeffortestimatetimestamp"    TIMESTAMP(6),
  "pyelapsedcustomerack"         NUMERIC(18, 0),
  "pyelapsedcustomerunsatisfied" NUMERIC(18, 0),
  "pyelapsedpastdeadline"        NUMERIC(18, 0),
  "pyelapsedpastgoal"            NUMERIC(18, 0),
  "pyelapsedstatusnew"           NUMERIC(18, 0),
  "pyelapsedstatusopen"          NUMERIC(18, 0),
  "pyelapsedstatuspending"       NUMERIC(18, 0),
  "pyeventid"                    VARCHAR(32),
  "pyfoldertype"                 VARCHAR(32),
  "pyid"                         VARCHAR(32),
  "pylabel"                      VARCHAR(64),
  "pyorigdivision"               VARCHAR(32),
  "pyorigorg"                    VARCHAR(32),
  "pyorigorgunit"                VARCHAR(32),
  "pyoriguserdivision"           VARCHAR(32),
  "pyoriguserid"                 VARCHAR(128),
  "pyoriguserworkgroup"          VARCHAR(64),
  "pyownerdivision"              VARCHAR(32),
  "pyownerorg"                   VARCHAR(32),
  "pyownerorgunit"               VARCHAR(32),
  "pyprimarycontact"             VARCHAR(64),
  "pyproblemreason"              VARCHAR(64),
  "pyproblemsource"              VARCHAR(64),
  "pyproblemtype"                VARCHAR(64),
  "pyreopencount"                NUMERIC(18, 0),
  "pyreopentimestamp"            TIMESTAMP(6),
  "pyresolutioncomplexity"       VARCHAR(8),
  "pyresolutioncost"             NUMERIC(18, 0),
  "pyresolveddivision"           VARCHAR(32),
  "pyresolvedorg"                VARCHAR(32),
  "pyresolvedorgunit"            VARCHAR(32),
  "pyresolvedtime"               VARCHAR(32),
  "pyresolvedtimestamp"          TIMESTAMP(6),
  "pyresolveduserid"             VARCHAR(128),
  "pyresolveduserworkgroup"      VARCHAR(64),
  "pyrootcause"                  VARCHAR(64),
  "pysladeadline"                TIMESTAMP(6),
  "pyslagoal"                    TIMESTAMP(6),
  "pyslaname"                    VARCHAR(32),
  "pystatuscustomersat"          VARCHAR(32),
  "pystatuswork"                 VARCHAR(32),
  "pyworklistdate1"              VARCHAR(8),
  "pyworklistdatetime1"          TIMESTAMP(6),
  "pyworklistdatetime2"          TIMESTAMP(6),
  "pyworklistdecimal1"           NUMERIC(18, 0),
  "pyworklistdecimal2"           NUMERIC(18, 0),
  "pyworklistinteger1"           NUMERIC(18, 0),
  "pyworklisttext1"              VARCHAR(128),
  "pyworklisttext2"              VARCHAR(128),
  "pyworklisttext3"              VARCHAR(128),
  "pxcurrentstagelabel"          VARCHAR(128),
  "pxcurrentstage"               VARCHAR(32),
  "pzinskey"                     VARCHAR(255) NOT NULL,
  "pzpvstream"                   BYTEA,
  "pxcommitdatetime"             TIMESTAMP(6),
  "pxsavedatetime"               TIMESTAMP(6),
  CONSTRAINT "pc_ninja_demo_pk" PRIMARY KEY ("pzinskey")
);